version: '3'
services:

  superset:
    # image: ghcr.io/ezynook/superset/superset:v1
    build: .
    container_name: superset
    restart: always
    ports:
      - 8088:8088
      - 5432:5432
    volumes:
      - superset_db:/var/lib/postgresql/15/main
    command: /bin/bash -c "/superset/softnix.sh"

volumes:
  superset_db: